Add bookmarks list menu
rgthree/rgthree-comfy pull request #198
Opened 2024-04-17 22:09 UTC by DrJKL

Also adds a label property to them. Think it…'s worth exposing it on hover as a pseudo-title?

## Label property
![image](https://github.com/rgthree/rgthree-comfy/assets/448862/cb87f370-f250-4f88-a9e8-3c4816b3047f)

## Bookmark context menu items
![image](https://github.com/rgthree/rgthree-comfy/assets/448862/b8edac3b-ec53-4041-8dd0-a11083cf6a52)

## Settings
![image](https://github.com/rgthree/rgthree-comfy/assets/448862/cd197707-1064-4bd8-a1ee-2e49c85d156a)

2024-04-17 23:25 UTC, DrJKL commented
[Discussion](https://github.com/rgthree/rgthree-comfy/discussions/196)

2024-04-20 04:13 UTC, rgthree commented on rgthree_config.json.default
> +    "bookmark_menu": {
It's hard to decide if this is a menu feature, or a bookmarks feature; but the other menu features have the `menu_` prefix, so let's change this to `menu_bookmarks` for consistency.

2024-04-20 04:13 UTC, rgthree commented on src_web/comfyui/bookmark.ts
> +const PROPERTY_LABEL = "label";
I like this idea but, ultimately, I think this introduces too many ways to "name" this node. Let's pull out the label property and just rely on the node.title _(yes, I didn't do a good job of encouraging changing the title by making it just the icon to begin with, but that's changed and I think just having one way to "name" the node will be more intuitive).

Also, I realize this means we don't need the `labeled_only` config option. I think that's OK for now. I'd rather keep it simple and see if there's real demand for a filter; my personal take is if it's important enough for a bookmark, then it's find to take 14px of space in the menu.

2024-04-20 04:13 UTC, rgthree commented on src_web/comfyui/rgthree.ts
> +    function getBookmarks(): ContextMenuItem[] {
Can you pull this out to a file-level function? Nothing in here needs the closure AFAICT. Keep the config check here outside the function though, please.

```typescript
const showBookmarks = CONFIG_SERVICE.getFeatureValue("bookmark_menu.enabled");
const bookmarkMenuItems = showBookmarks ? getBookmarks() : [];
```

2024-04-20 04:13 UTC, rgthree commented on src_web/comfyui/rgthree.ts
> +          .sort((a, b) => a.shortcutKey.localeCompare(b.shortcutKey));
I think we should sort by title to start. I do like the way the screenshot is sorted by shortcut ([1]. [2]), however, I have a feeling some ppl set shortcut keys by the near functionality (like "c" for "control net" and "i" for "inpainting" etc). If we sort by title, then we do give an easy option for ppl to change the sort by changing the title (but otherwise keeping the shortcut key the same)

2024-04-20 04:13 UTC, rgthree commented on src_web/comfyui/rgthree.ts
> +          content: "🔖 Bookmarks",
Only return the bookmarks title if there are also bookmarks items. If there are no items, please return an empty list (especially since this is auto enabled).

2024-04-20 04:13 UTC, rgthree commented
I like this. I want to simplify it a just a bit. Left some comments in the PR!

2024-04-20 08:35 UTC, DrJKL commented on rgthree_config.json.default
> +    "bookmark_menu": {
Makes sense to me, moved it to be adjacent to the other `menu_` features.

2024-04-20 08:35 UTC, DrJKL commented on src_web/comfyui/bookmark.ts
> +const PROPERTY_LABEL = "label";
For the node I made before I found this one, I have it collapse to just the icon and reveal the name when expanded: https://github.com/DrJKL/ComfyUI-Anchors/blob/18939d627d3631294f449c0aa9fbbea0e8ea3605/lib/AnchorNode.ts#L37

2024-04-20 08:58 UTC, DrJKL commented
Okay, I think I got everything.

2024-04-21 21:10 UTC, rgthree requested changes
Looks good. Just a couple small tweaks and it's ready.

2024-04-21 21:10 UTC, rgthree commented on src_web/comfyui/rgthree.ts
> +    .sort((a, b) => a.title.localeCompare(b.title));
I think you can just do all the work in one stream. Sort and map won't do anywork if there's no bookmarks (and array.sort also sorts in place anyway, so bookmarksToList is kind of redundant).

```typescript
// Filter all nodes for bookmarks, sort by title (for now), and generate menu items.
const bookmarks = graph._nodes
  .filter((n): n is Bookmark => n.type === NodeTypesString.BOOKMARK)
  .sort((a, b) => a.title.localeCompare(b.title))
  .map((n) => ({
    content: `[${n.shortcutKey}] ${n.title}`,
    className: "rgthree-contextmenu-item",
    callback: () => {
      n.canvasToBookmark();
    },
  }));

return !bookmarks.length ? [] : [
    {
      content: "🔖 Bookmarks",
      disabled: true,
      className: "rgthree-contextmenu-item rgthree-contextmenu-label",
    },
    ...bookmarks ,
  ];
```

2024-04-21 23:27 UTC, DrJKL commented on src_web/comfyui/rgthree.ts
> +    (n): n is Bookmark => n.type == NodeTypesString.BOOKMARK,
Done.

2024-04-21 23:27 UTC, DrJKL commented on src_web/comfyui/rgthree.ts
> +    .sort((a, b) => a.title.localeCompare(b.title));
Sounds good.

2024-05-04 19:31 UTC, rgthree approved these changes

2024-05-04 19:31 UTC, rgthree commented on web/comfyui/config.js
> +        {
Can you pull this up to under the "features.menu_auto_nest.subdirs" item, and add "(Menu)" to the start of the label (to match the other menu items). Also, add a period to the end of the description please :)

2024-05-05 07:35 UTC, DrJKL commented on web/comfyui/config.js
> +        {
Done. :-)

2024-05-05 17:54 UTC, rgthree commented on web/comfyui/config.js
> +        {
Perfect, but can you do from the source .ts file along with the JS? :)

2024-05-06 02:46 UTC, DrJKL commented on web/comfyui/config.js
> +        {
... This was a trap, wasn't it? :-P

2024-05-06 23:52 UTC, merged